version: '3.7'

services:
  whoami:
    image: containous/whoami
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.com`)" # custom domain
      - "traefik.http.services.whoami-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
