version: '3.7'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.1.3
    restart: always
    networks:
     -  traefik
    ports:
      - 80:80
      - 443:443
    command: --api --providers.docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/log/traefik:/var/log/traefik/"
      - "$PWD/config/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "$PWD/config/:/etc/traefik/config/"

networks:
  traefik:
    external: true
